### ISSUE TITLE
No reference to what-input in documentation for version 6

### ISSUE THREAD

**Issue by pscdodd** [foundation/foundation-rails#183]
The readme is missing a reference to the js library "[what-input](https://github.com/ten1seven/what-input)". According to the [Zurb Foundation installation docs](http://foundation.zurb.com/sites/docs/installation.html) and [Changelog](http://metroize.com/zurb-foundation-6-whats-new/) what-input is used instead of modernizr.

**Comment by tehpeh** [comment]
The absence of `what-input.js` will cause issues with Dropdown on the latest release (6.2.4, but fixed in https://github.com/zurb/foundation-sites/pull/9354).

In the meantime you can grab a [copy](https://github.com/ten1seven/what-input/releases/tag/v2.1.1), put it in `vendor/assets/javascripts` and require it in `application.js`.

More background on [what-input](https://github.com/zurb/foundation-sites/issues/8977)
