### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by ghost** [foundation/foundation-rails#225]
On a virigin rails app made purely to test this gem, I can't get any of the navigation components show on the Zurb website working. Is this a known problem?

**Comment by Deckluhm** [comment]
Can you put your app on GitHub and share the link here please?

**Comment by jeremyawhitman** [comment]
Certainly. I can do that this evening. 

--
Jeremy Whitman

**Comment by jeremyawhitman** [comment]
Here you go Arnaud,

https://github.com/jeremyawhitman/rails_foundation

**Comment by Deckluhm** [comment]
I don't have any issue with the app your provided.

You may have forgotten to restart your Rails server after installing the gem?

**Comment by jeremyawhitman** [comment]
I do apologize, I should have looked at that a bit harder at the app
yesterday before I sent it.

The problem I'm having is with any menu that has a drop down in it.

I have updated the application on git and I also attached a screenshot of
the problem.

It is using a copy and paste of the responsive menu from this page.
http://foundation.zurb.com/sites/docs/responsive-navigation.html
with some internal links added to replace the defaults.

I very much appreciate your help on this.

**Comment by bdesmarez** [comment]
Your problem comes from javascript not working due to turbolinks
I spent few hours to make it works
Follow this issue here to solve your problem https://github.com/zurb/foundation-rails/issues/201

If you're on Rails 5.1, you'll need to bring jQuery again and so remove the new ujs from Rails 5.1
`//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//# require rails-ujs`
