### ISSUE TITLE
foundation-rails 6.3.1.0 to 6.4.1.2 breaks responsive menu

### ISSUE THREAD

**Issue by pscdodd** [foundation/foundation-rails#234]
See http://foundation.zurb.com/forum/posts/38667-foundation-62-topbar-dropdown-issue

**Comment by ShadowRadiance** [comment]
Solution seems to be to ensure`_dropdown-menu.scss` is loaded after `_menu` in `vendor/assets/scss/foundation.scss` to fix the specificity issues. 

You can edit the `foundation_and_overrides.scss` file to move `@include foundation-dropdown-menu;` to the bottom of the list - that seems to fix it.

**Comment by CUnknown** [comment]
Yes, that seems to fix it!

**Comment by ignacio-gomez** [comment]
Thanks for the solution. I have spent hours trying to fix this issue

**Comment by EdgarPatron** [comment]
Yes, that seems to fix it!

**Comment by auranet** [comment]
thanks!   WFM.   I didn't need that afternoon anyway.....

**Comment by Fornacula** [comment]
Moving `@include foundation-dropdown-menu;` to the end of the list doesn't seem to fix the problem for me. Still having drop-down menu constantly showing up. Using **foundation-rails 6.4.3.0** with **rails 5.1.6**.

**Comment by arta** [comment]
Some version of this bug seems to be back. We noticed a few days ago. 

Tap on the dropdown menu item seems to go right through it to whatever is under (in the z-axis). 

One of our users "accidentally" deleted a file (by pressing "Yes, I am sure" on the alert, out of frustration). She wanted for the tapped menu item to take her to the resource. Instead, the Delete button underneath the menu item was tapped.

Rails 5.2.3, Foundation 6.5.3
